name: Project test
on: 
  push:
    paths:
      - src/**.java
jobs:
  test-proto:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java 8
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '8'
    - name: Build project
      run: ./build.sh
      shell: bash
    - name: Run Words2SigProto
      run: ./run.sh predictive.Words2SigProto
      shell: bash
    - name: Run Sigs2WordsProto
      run: ./run.sh predictive.Sigs2WordsProto
      shell: bash
