name: Project test
on: 
  push:
    paths:
      - src/**.java
jobs:
  test-proto:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Java 8
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '8'
    - name: Build project
      run: ./build.sh
      shell: bash
    - name: "Problem 1: Test prototype"
      run: ./test-proto.sh
      shell: bash
      continue-on-error: true
    - name: "Problem 2-3: Test dictionary implementations"
      run: ./test-dict.sh
      shell: bash
      continue-on-error: true
